[package]
name = "compiler"
version = "0.1.0"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.6.1"
bitflags = "1.3"
rustc-hash = "1.1.0"
json = "0.12.4"
phf = { version = "0.10", features = ["macros"] }

[dev-dependencies]
criterion = "0.3"
insta = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
smallvec = {version="1.2.0", features = ["serde"]}
