[workspace]
resolver = "2"
members = ["crates/*", "benches", "napi"]
default-members = ["crates/*"]

[profile.release]
lto = true

# [patch.crates-io]
# rslint_parser = { path = "../rslint/crates/rslint_parser" }
