[workspace]
resolver = "2"
members = ["crates/*", "benches"]
default-members = ["crates/*"]
version = "2021"

[profile.release]
lto = true

# [patch.crates-io]
# rslint_parser = { path = "../rslint/crates/rslint_parser" }
