name: Benchmark @vue canonical compiler
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run @vue/compiler-*
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.0
      - name: Run benchmark
        run: cd benches && pnpm install && npm run bench | tee output-js.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark @vue canonical compiler
          tool: 'benchmarkjs'
          output-file-path: benches/output-js.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@HerringtonDarkholme'
